### ISSUE TITLE
Remove CachePadded?

### ISSUE THREAD

**Issue by Amanieu** [crossbeam-rs/crossbeam-utils#10]
`#[repr(align(X))]` has been stabilized in 1.24. Is there still enough motivation to keep `CachePadded` around? It is much simpler to just annotate your struct with `#[repr(align(64))]` than to deal with a wrapper type.

**Comment by Amanieu** [comment]
Sorry, I just double-checked, it is stabilized in 1.25, not 1.24. This is the next release.

**Comment by stjepang** [comment]
I still find `CachePadded` useful. For example, suppose you want to implement a bounded queue. You might write something like this:

```rust
struct Queue<T> {
    head: AtomicUsize,
    tail: AtomicUsize,
    buffer: *const T,
}
```

It's a good idea to put these fields in different cache lines to prevent contention. Here's a try:

```rust
struct Queue<T> {
    head: Field<AtomicUsize>,
    tail: Field<AtomicUsize>,
    buffer: *const T,
}

#[repr(align(64))]
struct Field<T>(T);

impl<T> Deref for Field<T> {
    type Target = T;
    fn deref(&self) -> Self::Target {
        &self.0
    }
}
```

Alternatively, instead of implementing `Deref` we could access data with `self.head.0` rather than `self.head`. But that's a bit annoying...

Why not just do the following instead?

```rust
struct Queue<T> {
    head: CachePadded<AtomicUsize>,
    tail: CachePadded<AtomicUsize>,
    buffer: *const T,
}
```

Another benefit of `CachePadded` is that it might choose different alignment depending on architecture (with `#[cfg(...)]`). We currently don't do this since all major architectures have 64 byte long cache lines anyway, but we *could* do this in the future for more esoteric architectures.

`CachePadded` is also a really nice name and reads better than `#[repr(align(64))] // aligned to the length of a cache line`.

Finally, this might be a personal preference, but I generally prefer aligning data for optimization purposes myself where it is actually *used* rather than marking its *type* as aligned.

**Comment by stjepang** [comment]
@Amanieu What's your current opinion on this?

**Comment by Amanieu** [comment]
I think that we can keep `CachePadded` but simplify the implementation a lot once we decide to drop support for pre-1.25 rust.

**Comment by jeehoonkang** [comment]
I agree with @Amanieu.
