### ISSUE TITLE
spawn_unchecked and builder_spawn_unchecked should return ScopedJoinHandle<T>

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-utils#25]
Currently they return a `ScopedJoinHandle<()>`.

**Comment by jeehoonkang** [comment]
Are you meaning that `spawn_unchecked` returns `JoinHandle<()>` rather than `JoinHandle<T>`, right?

It seems it's hard to do so right now.  First of all, `JoinHandle<T>` requires `T: 'static`, while `spawn_unchecked` doesn't require `T`.  So the best we can get may be `JoinHandle<[u8; mem::size_of::<T>()]>`, but it's impossible to do so right now, too: https://github.com/rust-lang/rust/issues/43408

**Comment by stjepang** [comment]
Yeah, so ideally we'd want to relax the bounds on the returned type `T` by requiring `T: 'a` but right now we have to settle with `T: 'static`.
